### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by signeschloer** [robjameswall/dhitools#2]
Hi. I have found an indentation error in dfs.py. 
See attached picture. Line 223 should be inside the for loop.

![Capture](https://user-images.githubusercontent.com/48772503/55033165-ccf8c680-5012-11e9-9320-757f080cb85f.PNG)

Thanks for sharing your great code!

**Comment by robjameswall** [comment]
Hi, thanks for finding this bug. I've fixed and update this now
